---
# to change the default docker0 bridge subnet
#docker_bip : '10.123.0.1/16'

#docker_dns_resolvers : 
#  - '8.8.8.8'
#  - '8.8.4.4'

#docker_insecure_registries:
#  - 'localhost:5000'
#  - 'https://trusted-remote-registry.mydomain'

docker_mirror: 'https://get.docker.com'
docker_group: docker

docker_remote: False
docker_remote_bind: 0.0.0.0
docker_tls: True
docker_nontls_port: 2375
docker_tls_port: 2376

docker_pki_key_suffix: '-key.pem'
docker_pki_cert_suffix: '.pem'
docker_pki_dir: '~/pki'
